version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    working_dir: /app
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - 8080:8080
    environment:
      - DB_USER=root
      - DB_PASSWORD=secret
      - DB_HOST=eulabs_challange_api-db
      - DB_PORT=3306
      - DB_NAME=eulabs_challenge_api
      - DB_CHARSET=utf8mb4
      - DB_PARSETIME=True
      - DB_LOC=Local
      - PORT=8080
    networks:
      default:
        aliases:
          - eulabs_challange_api-dev

  mysql:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=eulabs_challenge_api
      - MYSQL_ROOT_PASSWORD=secret
    ports:
      - '3306:3306'
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 20s
      retries: 10
    networks:
      default:
        aliases:
          - eulabs_challange_api-db

networks:
  default:
    name: eulabs
